version: '3'
services:
  my-app:
    image: <usaername>/my-app:0.1
    ports:
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    volumes:
      - mongo-data:/data/db
    enviroment:
     - MONGO_INITDB_ROOT_USERNAME=admin 
     - MONGO_INITDB_ROOT_PASSWORD=password
    
  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    enviroment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER="mongodb"  

volumes:
  mongo-data:
    driver: local